version: "3"
services:
    influxdb:
      image: influxdb
      ports: 
      - "8086:8086"
    # telegraf:
    #   image: telegraf
    #   volumes: 
    #   - "./telegraf.conf:/etc/telegraf/telegraf.conf"
    chronograf:
      image: chronograf
      ports:
      - "8888:8888"
      command: --influxdb-url=http://influxdb:8086
    kapacitor:
      image: kapacitor
      volumes: 
      - "./kapacitor.conf:/etc/kapacitor/kapacitor.conf"
      environment:
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"
      ports:
      - "9092:9092"
    benthos:
      image: jeffail/benthos
      volumes:
      - "./conf/webhook.yaml:/benthos.yaml"
      ports:
      - "4195:4195"
    smtp2http:
      image: dalongrong/smtp2http
      command: --listen=:25 --webhook=http://benthos:4195/ --strict=false